version: '3.1'

services:
  everdade-crawler:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always  

  scheduler:
    build: https://github.com/mcuadros/ofelia.git
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ofelia/config.ini:/etc/ofelia/config.ini
    depends_on:
      - everdade-crawler

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017   
    env_file:
      - .env
    volumes:
      - /root/fact_check_crawler/data/:/data/db


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    