version: '3.1'

services:
  everdade-crawler:
    container_name: everdade_crawler
    build: 
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    restart: always  
    networks:
      - everdade-net

  scheduler:
    build: https://github.com/mcuadros/ofelia.git
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ofelia/config.ini:/etc/ofelia/config.ini
    depends_on:
      - everdade-crawler
    networks:
      - everdade-net

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017   
    env_file:
      - .env
    volumes:
      - /root/fact_check_crawler_db/data/:/data/db
    networks:
      - everdade-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    networks:
      - everdade-net
    
networks:
  everdade-net:
    driver: bridge
